import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, CheckCircle2, CircleHelp, Clock3, DatabaseZap, Link2, LockKeyhole, Plus, RefreshCw, Settings2, X } from 'lucide-react'
import { WorkspaceShell } from '../components/WorkspaceShell'
import { useStore } from '../data/store'
import { createListingSource, listListingSources, type ListingSource } from '../lib/productionWorkflow'
import { isDemoMode } from '../lib/runtime'

const sourceTypes = [
  { title: 'MLS / RESO', kind: 'mls_reso' as const, detail: 'Connect an approved MLS or RESO Data Dictionary feed.', icon: DatabaseZap },
  { title: 'CRM', kind: 'crm' as const, detail: 'Connect a CRM that has a supported server-side integration.', icon: Link2 },
  { title: 'Other supported source', kind: 'other' as const, detail: 'Prepare another approved listing platform for integration.', icon: Settings2 },
]

function sourceLabel(kind: ListingSource['kind']) {
  return kind === 'mls_reso' ? 'MLS / RESO' : kind === 'crm' ? 'CRM' : 'Other source'
}

export function ListingSourcesScreen() {
  const { workspace } = useStore()
  const [sources, setSources] = useState<ListingSource[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [kind, setKind] = useState<ListingSource['kind'] | null>(null)
  const [name, setName] = useState('')
  const [endpoint, setEndpoint] = useState('')
  const [saving, setSaving] = useState(false)

  const load = () => {
    if (isDemoMode || !workspace?.id) { setLoading(false); return }
    setLoading(true)
    listListingSources(workspace.id).then(setSources).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load listing sources.')).finally(() => setLoading(false))
  }
  useEffect(load, [workspace?.id])

  const openCreate = (nextKind: ListingSource['kind']) => { setKind(nextKind); setName(''); setEndpoint(''); setError(null) }
  const save = async (event: React.FormEvent) => {
    event.preventDefault()
    if (!workspace?.id || !kind) return
    setSaving(true); setError(null)
    try {
      await createListingSource(workspace.id, { name: name.trim(), kind, endpoint: endpoint.trim() || undefined })
      setKind(null); load()
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save the listing source.') } finally { setSaving(false) }
  }

  return <WorkspaceShell><><main className="min-h-full bg-canvas pb-12 text-ink"><div className="mx-auto max-w-[1280px] px-5 py-8 sm:px-8 lg:px-10">
    <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[11px] font-bold text-ink-2">Settings <span className="mx-1.5 text-ink-3">›</span> Listing Sources</p><h1 className="mt-4 text-[32px] font-extrabold tracking-[-0.04em]">Listing Sources</h1><p className="mt-1.5 max-w-[600px] text-[12px] text-ink-2">Prepare the sources your team uses to bring listing information into OpenHouse.</p></div><button type="button" onClick={() => openCreate('other')} disabled={!workspace?.id || isDemoMode} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-[11px] font-bold text-white shadow-subtle hover:bg-primary-hover disabled:cursor-not-allowed disabled:opacity-50"><Plus size={15} /> Connect source</button></header>
    {error && <p role="alert" className="mt-5 rounded-xl border border-danger/30 bg-danger/5 px-4 py-3 text-[12px] text-danger">{error}</p>}
    <section className="mt-7 grid overflow-hidden rounded-2xl border border-border bg-surface shadow-subtle sm:grid-cols-3"><div className="flex items-center gap-3 px-5 py-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-primary/10 text-primary"><Link2 size={17} /></span><span><span className="block text-[20px] font-extrabold tracking-tight">{sources.length}</span><span className="block text-[10.5px] text-ink-2">Configured sources</span></span></div><div className="flex items-center gap-3 border-t border-border px-5 py-4 sm:border-l sm:border-t-0"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#e8eff6] text-info"><DatabaseZap size={17} /></span><span><span className="block text-[20px] font-extrabold tracking-tight">0</span><span className="block text-[10.5px] text-ink-2">Listings available</span></span></div><div className="flex items-center gap-3 border-t border-border px-5 py-4 sm:border-l sm:border-t-0"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-raised-2 text-ink-2"><Clock3 size={17} /></span><span><span className="block text-[14px] font-extrabold tracking-tight">No sync yet</span><span className="block text-[10.5px] text-ink-2">Requires an active provider</span></span></div></section>
    <div className="mt-7 grid gap-5 xl:grid-cols-[minmax(0,1fr)_275px]"><div><h2 className="text-[16px] font-bold">Configured sources</h2>{loading ? <section className="mt-3 h-36 animate-pulse rounded-2xl border border-border bg-surface" /> : sources.length === 0 ? <section className="mt-3 rounded-2xl border border-dashed border-line-strong bg-surface px-6 py-12 text-center shadow-subtle"><span className="mx-auto flex h-11 w-11 items-center justify-center rounded-full bg-primary/10 text-primary"><Link2 size={20} /></span><h3 className="mt-4 text-[16px] font-bold">Prepare your first listing source</h3><p className="mx-auto mt-1 max-w-[430px] text-[12px] leading-relaxed text-ink-2">Start a source record here, then complete provider approval, server-side credentials, field mapping, and a test sync before OpenHouse can activate it.</p></section> : <section className="mt-3 divide-y divide-border/60 overflow-hidden rounded-2xl border border-border bg-surface shadow-subtle">{sources.map((source) => <article key={source.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><div className="flex items-center gap-2"><h3 className="text-[14px] font-bold">{source.name}</h3><span className="rounded-full bg-raised-2 px-2 py-0.5 text-[10px] font-bold text-ink-2">{source.status}</span></div><p className="mt-1 text-[11px] text-ink-2">{sourceLabel(source.kind)}{source.endpoint ? ` · ${source.endpoint}` : ''}</p></div><span className="text-[11px] font-semibold text-ink-3">Provider setup required</span></article>)}</section>}<h2 className="mt-7 text-[16px] font-bold">Add a new source</h2><section className="mt-3 grid overflow-hidden rounded-2xl border border-border bg-surface shadow-subtle md:grid-cols-3">{sourceTypes.map(({ title, kind: sourceKind, detail, icon: Icon }, index) => <button key={title} type="button" onClick={() => openCreate(sourceKind)} disabled={!workspace?.id || isDemoMode} className={`group flex min-h-[150px] flex-col items-start p-5 text-left transition-colors hover:bg-raised disabled:cursor-not-allowed disabled:opacity-50 ${index ? 'border-t border-border md:border-l md:border-t-0' : ''}`}><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon size={17} /></span><h3 className="mt-4 text-[12px] font-bold">{title}</h3><p className="mt-1 text-[10.5px] leading-relaxed text-ink-2">{detail}</p><span className="mt-auto pt-3 text-[11px] font-bold text-primary">Start setup <ArrowRight size={13} className="inline" /></span></button>)}</section><p className="mt-4 flex gap-2 text-[10.5px] leading-relaxed text-ink-2"><LockKeyhole size={14} className="mt-0.5 shrink-0 text-primary" />Provider credentials belong in Supabase secrets or the provider’s OAuth connection—not in this browser form or property data.</p></div>
      <aside className="h-fit rounded-2xl border border-border bg-surface p-4 shadow-subtle"><div className="flex items-center justify-between"><h2 className="text-[14px] font-bold">Sync activity</h2><RefreshCw size={15} className="text-ink-3" /></div><div className="mt-4 border-t border-border pt-3 text-center"><p className="text-[11px] font-semibold text-ink">No sync activity</p><p className="mt-1 text-[10px] leading-relaxed text-ink-2">A source stays in draft until an approved server-side provider adapter validates it.</p></div><div className="mt-5 border-t border-border pt-4"><h3 className="text-[12px] font-bold">Connection principles</h3><ul className="mt-3 space-y-3 text-[10.5px] leading-relaxed text-ink-2"><li className="flex gap-2"><CheckCircle2 size={13} className="mt-0.5 shrink-0 text-primary" />Review listings before adding them.</li><li className="flex gap-2"><CheckCircle2 size={13} className="mt-0.5 shrink-0 text-primary" />Keep field mappings explicit and versioned.</li><li className="flex gap-2"><CheckCircle2 size={13} className="mt-0.5 shrink-0 text-primary" />Nothing publishes automatically.</li></ul></div><Link to="/imported-listings" className="mt-5 flex items-center justify-between border-t border-border pt-4 text-[11px] font-bold text-primary">Imported Listings <ArrowRight size={13} /></Link></aside></div>
    <div className="mt-6 flex items-start gap-2 rounded-xl border border-border bg-surface p-3 text-[10.5px] leading-relaxed text-ink-2"><CircleHelp size={15} className="mt-0.5 shrink-0 text-primary" />A source record is not an active integration. Before activation we need the provider you have a contract with, its authentication method, approved scopes, server-side secret/OAuth storage, field mappings, a safe sync worker, and test listings.</div>
  </div></main>{kind && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-5"><form onSubmit={save} className="w-full max-w-md rounded-2xl border border-border bg-surface p-6 shadow-card"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-primary">Source setup</p><h2 className="mt-1 text-[20px] font-extrabold">Add {sourceLabel(kind)}</h2></div><button type="button" onClick={() => setKind(null)} className="rounded-lg p-1 text-ink-3 hover:bg-raised"><X size={18} /></button></div><p className="mt-3 text-[12px] leading-relaxed text-ink-2">This creates a private draft record only. It does not accept provider credentials or activate syncing.</p><label className="mt-5 block"><span className="mb-2 block text-[11px] font-bold">Source name</span><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. My MLS feed" className="w-full rounded-lg border border-border bg-surface px-3 py-2.5 text-[13px] outline-none focus:border-primary" /></label><label className="mt-4 block"><span className="mb-2 block text-[11px] font-bold">Public endpoint <span className="font-normal text-ink-3">(optional)</span></span><input value={endpoint} onChange={(event) => setEndpoint(event.target.value)} placeholder="https://provider.example/api" className="w-full rounded-lg border border-border bg-surface px-3 py-2.5 text-[13px] outline-none focus:border-primary" /></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setKind(null)} className="rounded-lg border border-border px-4 py-2.5 text-[12px] font-bold hover:bg-raised">Cancel</button><button disabled={saving || !name.trim()} className="rounded-lg bg-primary px-4 py-2.5 text-[12px] font-bold text-white disabled:opacity-60">{saving ? 'Saving…' : 'Save draft source'}</button></div></form></div>}</></WorkspaceShell>
}

